### ISSUE TITLE
Como mostrar o extrato detalhado como mostrado App?

### ISSUE THREAD

**Issue by isomiluizdasilva** [nexy/phpnubank#1]
Bom dia. 
Inicialmente parabenizo pela valiosíssima iniciativa da API. Muito Show!!!
Gostaria de tirar uma dúvida. A demonstração dos dados mostrados na tela, constam somente:
---
Transferência recebida 2022-06-23
R$ 0,05
---

Como faço para mostrar
---
Transferência recebida 2022-06-23
R$ 0,05
+++++++ Identificador/Descrição: ??
+++++++ Identificador: ??
---

Como mostrado no anexo.
![capturatela_04072022_123109](https://user-images.githubusercontent.com/61293748/177185079-41a36edd-46fe-4d84-ac79-aec230612364.png)

**Comment by isomiluizdasilva** [comment]
Melhor, como pegar o todos os IDs das transações PIX do dia?

**Comment by ramcoelho** [comment]
Infelizmente o NuBank parou de enviar os IDs de transação na API aberta. Inicialmente eles limitaram apenas a contas de pessoas jurídicas, mas por fim removeram em definitivo. A explicação extraoficial é que apenas empresas reguladas pelo Bacen podem ter acesso a estas informações, o que nos força a contratar uma API de uma Fintech regulada.

Sinto não poder ajudar mais, mas espero que as informações acima sirvam para dar um norte.

Sucesso.
